sudo: required

language: go
go:
  - 1.8

services:
  - docker

before_install:
  - cd docker
  - docker build -t "metacurrency/holochain" .
  - cd ..

script:
  - make
  # - TEST_FLAGS='-v -coverprofile=$(pkg_path)/coverage.txt -covermode=atomic' make -e test

cache:
    directories:
        - $GOPATH/src/gx

after_success:
  # - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" == "322-process-for-keeping-dockerfile-up-to-date" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push metacurrency/holochain;
    fi
