os:
  - linux

language: go
go:
  - 1.8.x
  - 1.9.x

script:
  - make hcdev
  - TEST_FLAGS='-v -coverprofile=$(pkg_path)/coverage.txt -covermode=atomic' make -e test

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
    directories:
        - $GOPATH/src/gx
