Version = 0
UUID = "00000000-0000-0000-0000-000000000000"
Name = "sample"
PropertiesSchemaFile = "properties_schema.json"
RequiresVersion = 0

[Properties]
  description = "a bogus test holochain"
  language = "en"

[BasedOn]

[[Zomes]]
  Name = "zySampleZome"
  Description = "this is a zygomas test zome"
  Code = ""
  CodeFile = "zySampleZome.zy"
  RibosomeType = "zygo"

  [[Zomes.Entries]]
    Name = "evenNumbers"
    DataFormat = "zygo"
    Schema = ""
    SchemaFile = ""
    Sharing = "public"

  [[Zomes.Entries]]
    Name = "primes"
    DataFormat = "json"
    Schema = ""
    SchemaFile = "primes.json"
    Sharing = "public"

  [[Zomes.Entries]]
    Name = "profile"
    DataFormat = "json"
    Schema = ""
    SchemaFile = "profile.json"
    Sharing = "public"

  [[Zomes.Functions]]
    Name = "getDNA"
    CallingType = "string"
    Exposure = ""

  [[Zomes.Functions]]
    Name = "addEven"
    CallingType = "string"
    Exposure = "public"

  [[Zomes.Functions]]
    Name = "addPrime"
    CallingType = "json"
    Exposure = "public"

  [[Zomes.Functions]]
    Name = "testStrFn1"
    CallingType = "string"
    Exposure = ""

  [[Zomes.Functions]]
    Name = "testStrFn2"
    CallingType = "string"
    Exposure = ""

  [[Zomes.Functions]]
    Name = "testJsonFn1"
    CallingType = "json"
    Exposure = ""

  [[Zomes.Functions]]
    Name = "testJsonFn2"
    CallingType = "json"
    Exposure = ""

[[Zomes]]
  Name = "jsSampleZome"
  Description = "this is a javascript test zome"
  Code = ""
  CodeFile = "jsSampleZome.js"
  RibosomeType = "js"

  [[Zomes.Entries]]
    Name = "oddNumbers"
    DataFormat = "js"
    Schema = ""
    SchemaFile = ""
    Sharing = "public"

  [[Zomes.Entries]]
    Name = "profile"
    DataFormat = "json"
    Schema = ""
    SchemaFile = "profile.json"
    Sharing = "public"

  [[Zomes.Entries]]
    Name = "rating"
    DataFormat = "links"
    Schema = ""
    SchemaFile = ""
    Sharing = ""

  [[Zomes.Entries]]
    Name = "secret"
    DataFormat = "string"
    Schema = ""
    SchemaFile = ""
    Sharing = ""

  [[Zomes.Functions]]
    Name = "getProperty"
    CallingType = "string"
    Exposure = ""

  [[Zomes.Functions]]
    Name = "addOdd"
    CallingType = "string"
    Exposure = "public"

  [[Zomes.Functions]]
    Name = "addProfile"
    CallingType = "json"
    Exposure = "public"

  [[Zomes.Functions]]
    Name = "testStrFn1"
    CallingType = "string"
    Exposure = ""

  [[Zomes.Functions]]
    Name = "testStrFn2"
    CallingType = "string"
    Exposure = ""

  [[Zomes.Functions]]
    Name = "testJsonFn1"
    CallingType = "json"
    Exposure = ""

  [[Zomes.Functions]]
    Name = "testJsonFn2"
    CallingType = "json"
    Exposure = ""

[DHTConfig]
  HashType = "sha2-256"

[Progenitor]
  Name = "Example Agent <example@example.com"
  PubKey = [8, 1, 18, 32, 193, 43, 31, 148, 23, 249, 163, 154, 128, 25, 237, 167, 253, 63, 214, 220, 206, 131, 217, 74, 168, 30, 215, 237, 231, 160, 69, 89, 48, 17, 104, 210]
