Version = 0
Id = "00000000-0000-0000-0000-000000000000"
Name = "sample"
PropertiesSchema = "properties_schema.json"
HashType = "sha2-256"
RequiresVersion = 4

[Properties]
  description = "a bogus test holochain"
  language = "en"

[BasedOn]

[Zomes]
  [Zomes.jsSampleZome]
    Name = "jsSampleZome"
    Description = "this is a javascript test zome"
    Code = "jsSampleZome.js"
    NucleusType = "js"
    [Zomes.jsSampleZome.CodeHash]
    [Zomes.jsSampleZome.Entries]
      [Zomes.jsSampleZome.Entries.oddNumbers]
        Name = "oddNumbers"
        DataFormat = "js"
        Schema = ""
        Sharing = "public"
        [Zomes.jsSampleZome.Entries.oddNumbers.SchemaHash]
      [Zomes.jsSampleZome.Entries.profile]
        Name = "profile"
        DataFormat = "json"
        Schema = "profile.json"
        Sharing = ""
        [Zomes.jsSampleZome.Entries.profile.SchemaHash]
      [Zomes.jsSampleZome.Entries.rating]
        Name = "rating"
        DataFormat = "links"
        Schema = ""
        Sharing = ""
        [Zomes.jsSampleZome.Entries.rating.SchemaHash]

    [[Zomes.jsSampleZome.Functions]]
      Name = "getProperty"
      CallingType = "string"

    [[Zomes.jsSampleZome.Functions]]
      Name = "addOdd"
      CallingType = "string"

    [[Zomes.jsSampleZome.Functions]]
      Name = "addProfile"
      CallingType = "json"

    [[Zomes.jsSampleZome.Functions]]
      Name = "testStrFn1"
      CallingType = "string"

    [[Zomes.jsSampleZome.Functions]]
      Name = "testStrFn2"
      CallingType = "string"

    [[Zomes.jsSampleZome.Functions]]
      Name = "testJsonFn1"
      CallingType = "json"

    [[Zomes.jsSampleZome.Functions]]
      Name = "testJsonFn2"
      CallingType = "json"
  [Zomes.zySampleZome]
    Name = "zySampleZome"
    Description = "this is a zygomas test zome"
    Code = "zySampleZome.zy"
    NucleusType = "zygo"
    [Zomes.zySampleZome.CodeHash]
    [Zomes.zySampleZome.Entries]
      [Zomes.zySampleZome.Entries.evenNumbers]
        Name = "evenNumbers"
        DataFormat = "zygo"
        Schema = ""
        Sharing = "public"
        [Zomes.zySampleZome.Entries.evenNumbers.SchemaHash]
      [Zomes.zySampleZome.Entries.primes]
        Name = "primes"
        DataFormat = "json"
        Schema = ""
        Sharing = "public"
        [Zomes.zySampleZome.Entries.primes.SchemaHash]
      [Zomes.zySampleZome.Entries.profile]
        Name = "profile"
        DataFormat = "json"
        Schema = "profile.json"
        Sharing = ""
        [Zomes.zySampleZome.Entries.profile.SchemaHash]

    [[Zomes.zySampleZome.Functions]]
      Name = "getDNA"
      CallingType = "string"

    [[Zomes.zySampleZome.Functions]]
      Name = "addEven"
      CallingType = "string"

    [[Zomes.zySampleZome.Functions]]
      Name = "addPrime"
      CallingType = "json"

    [[Zomes.zySampleZome.Functions]]
      Name = "testStrFn1"
      CallingType = "string"

    [[Zomes.zySampleZome.Functions]]
      Name = "testStrFn2"
      CallingType = "string"

    [[Zomes.zySampleZome.Functions]]
      Name = "testJsonFn1"
      CallingType = "json"

    [[Zomes.zySampleZome.Functions]]
      Name = "testJsonFn2"
      CallingType = "json"
