version: '3'

services:
  chainjoincontainer:
    build:
      context: .
      dockerfile: Dockerfile.joinService
    volumes:
      - ~/.holochain:/root/.holochain
  hc:
    build:
      context: .
    ports:
      - "3141"
    volumes:
      - ~/holochain/clutter:/chain.clutter
    depends_on: [chainjoincontainer]


