version: '3'

services:
  chainjoincontainer:
    build:
      context: .
      dockerfile: Dockerfile.joinService
    volumes:
      - ./chainData:/root/.holochain
  hc:
    build:
      context: .
    ports:
      - "3141"
    volumes:
      - ./chainData:/clutter

